=== saatkamp/simpl09/tags/iteration2/org.simpl.rrs.transformation/schema/rrs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://uni-stuttgart.de/simpl/rrs" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:rrs="http://uni-stuttgart.de/simpl/rrs">












	

	<xsd:complexType name="EPR">
		<xsd:sequence maxOccurs="1" minOccurs="1">
			<xsd:element name="address" type="xsd:anyURI"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="referenceProperties"
				type="rrs:ReferenceProperties" maxOccurs="1" minOccurs="1">
			</xsd:element>

			<xsd:element name="referenceParameters"
				type="xsd:string" maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="portType" type="xsd:QName" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="serviceName" type="rrs:ServiceName"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="policy" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="ReferenceProperties">

		<xsd:choice maxOccurs="1" minOccurs="1">
			<xsd:element name="resolutionSystem" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
		</xsd:choice>
	</xsd:complexType>
	






	<xsd:complexType name="ServiceName">

		<xsd:simpleContent>
			<xsd:extension base="xsd:QName">
				<xsd:attribute name="portName" type="xsd:NCName"></xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>


	<xsd:element name="epr" type="rrs:EPR"></xsd:element>
</xsd:schema>

=== saatkamp/simpl09/org.eclipse.references.model/model/rrs.xml
<?xml version="1.0" encoding="UTF-8"?>
<rrs:epr xmlns:rrs="http://uni-stuttgart.de/simpl/rrs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uni-stuttgart.de/simpl/rrs rrs.xsd ">
  <rrs:address>http://tempuri.org</rrs:address>
  <rrs:referenceProperties>
    <rrs:resolutionSystem>rrs:resolutionSystem</rrs:resolutionSystem>
  </rrs:referenceProperties>
  <rrs:referenceParameters>
    <rrs:referenceName>rrs:referenceName</rrs:referenceName>
    <rrs:statement>rrs:statement</rrs:statement>
  </rrs:referenceParameters>
  <rrs:portType>QName</rrs:portType>
  <rrs:serviceName portName="NCName">QName</rrs:serviceName>
  <rrs:policy>rrs:policy</rrs:policy>
</rrs:epr>
